set_probe_target:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: gmg
    probe:
      required: true
      selector:
        number:
          min: 1
          max: 2
          step: 1
          mode: box
    temperature:
      required: true
      selector:
        number:
          min: 32
          max: 257
          step: 1
          unit_of_measurement: "°F"
          mode: box

refresh:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: gmg
